version: "3.9"

services:
  reddit-scheduler:
    image: python:3.11-slim
    container_name: reddit-scheduler
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - reddit_data:/data
      - ./app:/app
    working_dir: /app
    environment:
      FLASK_SECRET_KEY: "change-this-to-a-secret"
      REDDIT_CLIENT_ID: "your-client-id"
      REDDIT_CLIENT_SECRET: "your-client-secret"
      REDDIT_USERNAME: "your-username"
      REDDIT_PASSWORD: "your-password"
      REDDIT_USER_AGENT: "reddit-scheduler/0.3 by u/your-username"
      UPLOAD_DIR: "/data/uploads"
      DB_FILE: "/data/posts.db"
      APP_TIMEZONE: "America/Chicago"
      MAX_UPLOAD_MB: "10"
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && python app.py"

volumes:
  reddit_data:
    driver: local