version: "3.9"

services:
  reddit-scheduler:
    build: .
    container_name: reddit-scheduler
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - REDDIT_CLIENT_ID=your_client_id
      - REDDIT_CLIENT_SECRET=your_client_secret
      - REDDIT_USERNAME=your_username
      - REDDIT_PASSWORD=your_password
      - REDDIT_USER_AGENT=reddit-scheduler
    restart: unless-stopped
