version: "3.9"

services:
  reddit-scheduler:
    build: .
    container_name: reddit-scheduler
    ports:
      - "5000:5000"
    volumes:
      - reddit_data:/data
      - ./app:/app
    environment:
      - FLASK_SECRET_KEY=change-this-to-a-secret
      - REDDIT_CLIENT_ID=your-client-id
      - REDDIT_CLIENT_SECRET=your-client-secret
      - REDDIT_USERNAME=your-username
      - REDDIT_PASSWORD=your-password
      - REDDIT_USER_AGENT=reddit-scheduler
      - UPLOAD_DIR=/data/uploads
      - DB_FILE=/data/posts.db
      - APP_TIMEZONE=America/Chicago
      - MAX_UPLOAD_MB=10
    restart: unless-stopped

volumes:
  reddit_data:
    driver: local
